name: Build And Deploy
on:
  push:
    branches:
     - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts  

      - name: Checkout Repo (SSH)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref_name }}
          fetch-depth: 1
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}

      # 下载go编译器
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.0'

      # 设置缓存目录和模块目录
      - name: Setup Go Cache Dirs
        run: |
          mkdir -p $HOME/.cache/go-build $HOME/go/pkg/mod
          go env -w GOCACHE=$HOME/.cache/go-build
          go env -w GOMODCACHE=$HOME/go/pkg/mod

      # 设置镜像
      - name: Use Go proxy
        run: |
          go env -w GOPROXY=https://goproxy.cn,direct

      # 下载依赖
      - name: Download deps
        run: go mod download

      # 编译项目
      - name: Build Go Project
        run: |
          mkdir -p ./build
          GOOS=linux GOARCH=amd64 go build -o ./build/myblog 

      - name: Deploy and Restart backend service
        run: |
          sudo install -m 0755 -o goapp -g goapp ./build/myblog /home/goapp/myblog.new
          sudo mv -f /home/goapp/myblog.new /home/goapp/myblog
          sudo systemctl restart myblog
          sudo systemctl --no-pager status myblog || true

